---
title: "Monthly Reports 2024"
editor: visual
format: 
  html:
    self-contained: true
    toc: true
    toc-depth: 2
    toc-expand: 2
    toc-location: left
---

Last compiled: `r Sys.Date()`

## September

### Website (\~ 16 hours)

-   **Minor updates**: building form, software list, profile pages

-   **Silktide**: Review reports and make corresponding updates

-   **Project support**: create code for header and footer

### Teaching (\~ 64 hours)

-   **R for Beginners**: update course work and teaching
-   **Streamlining Research and Literature Reviews Using A.I.**: preparation
-   **Tableau**: co-teach with Cynthia
-   **Student consultations for R programming**

### Research ( \~ 39 hours)

-   **Workshop**: AI tools in Education; CALA workshops on using AI in libraries

-   **Reading**: R for Data Analysis in Social Sciences, logistic regression

-   Interview for using AI in accessibility

-   Learning RAG techique

### Service (\~ 7 hours)

-   **IFLA S&E**: monthly meeting

-   **CFSA** meeting and distribution list and website maintenance

-   **AI working group meeting**

-   **Data visualization group meeting**

### Others (\~ 28 hours)

-   Responded queries through website email

-   Unit meeting

## August

### Website (\~ 23 hours)

-   **Website Redesign Plan:** set up objectives and timeline, added more details, and requested Hotjar subscription

-   **Library Maps, homepage links, and other minor updates**: demo map updates to Micah; updated OA awards, library hours, homepage links, style updates due to the implementation of the new global template, etc.

-   **Silktide**: Review reports and make corresponding updates.

### Teaching (\~ 60 hours)

-   **R for Beginners**: update course work

### Research ( \~ 20 hours)

-   DPI conference

-   Workshop: Adapting to Innovation & the Texas Landscape of AI

-   Reading: R for Data Analysis in Social Sciences

-   Online training material on Google Analytics 4

### Service (\~ 7 hours)

-   **IFLA S&E**: monthly meeting; investigated about the upcoming satellite meeting

-   **UX/Web Team meeting**: reported website updates

-   **AI working group meeting**

### Others (\~ 20 hours)

-   Responded queries through website email

-   Unit meeting

-   HR training

-   New laptop preparation and software installation

## **July**

### Website (\~ 20 hours)

-   Web access groups management
-   Silktide testing and website updates
-   Prepare for web redesign
-   Minor page updates to respond to requests

### Teaching (\~ 8 hours)

-   Prepared the workshop series of R4Beginners - updating content

### Research (\~ 67 hours)

-   Conference: 2024 useR!
-   Attended workshops organized by TAP Institute from Constellate
-   SkillType webinars
-   Workshop on Data visualization

### Service (\~ 2 hours)

-   IFLA
    -   Updated event pages;
    -   Uploaded 2 workshops to YouTube channel;
    -   Archived workshop related content to Google Drive
-   Attended AI working group meeting

### Others (\~ 16 hours)

-   Responded queries through website email

-   Conference preparation

## **June**

### Website

-   Updated library hours on Google profiles
-   Read through the update logs
-   Read documents on the new global template
-   Minor page updates to respond to requests

### Teaching

-   Prepared the workshop series of R4Beginners - updating content
-   Preparing for co-teaching with Brian on AI tools for researchers

### Research

-   Watched CNI digital scholarship webinar recordings
-   Attended workshop - Teaching and Learning with AI
-   Revisited CS50
-   Readings on AI coding assistants

### Service

-   IFLA
    -   Created event page, circulated event information on distribution lists;
    -   Created YouTube channel and uploaded 3 workshops;
    -   Created a Gmail for the S&E session and migrated all the session files to the new account; shared account information with the chair and secretary
    -   Attended monthly meeting
-   Attended AI working group meeting

### Others

-   Managed current and old emails
-   Responded queries through website emails
