project:
  type: website

website:
  title: "monthly-reports"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 2024.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

